apiVersion: v1
kind: Pod
metadata:
  name: host-pod
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: shell-container
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h "]
    volumeMounts:
    - mountPath: /host
      name: host-root
  volumes:
  - name: host-root
    hostPath:
      # directory location on host
      path: /
      # this field is optional
      type: ""
